name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-build:
    name: Build Web (PWA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Web
        run: npm run build

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/

  android-build:
    name: Build Android (APK)
    runs-on: ubuntu-latest
    needs: web-build
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Build Web Assets
        run: npm run build

      - name: Setup Capacitor Android
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  ios-build:
    name: Build iOS (IPA)
    runs-on: macos-latest
    needs: web-build
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Build Web Assets
        run: npm run build

      - name: Setup Capacitor iOS
        run: |
          npx cap add ios || true
          npx cap sync ios

      - name: Build iOS Archive (Unsigned)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -destination generic/platform=iOS \
            -archivePath App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export Unsigned IPA
        run: |
          cd ios/App
          # Create Payload directory required for IPA structure
          mkdir Payload
          # Copy the .app bundle from the archive to Payload
          cp -r App.xcarchive/Products/Applications/App.app Payload/
          # Zip it up to create the IPA
          zip -r App.ipa Payload

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: ios/App/App.ipa